"""Deterministic report content that works without an AI provider."""

from collections import Counter
from datetime import date


SEVERITY_ORDER = ("critical", "high", "medium", "low", "info")


def _value(value, fallback: str = "Not provided") -> str:
    if value is None or value == "":
        return fallback
    if isinstance(value, date):
        return value.isoformat()
    return str(value)


def _severity(finding) -> str:
    severity = finding.severity
    return severity.value if hasattr(severity, "value") else str(severity)


def _provenance_lines(finding) -> list[str]:
    lines = []
    for ref in getattr(finding, "evidence_refs", None) or []:
        details = [str(ref.get("id", "unknown"))]
        if ref.get("filename"):
            details.append(str(ref["filename"]))
        elif ref.get("scan_type"):
            details.append(str(ref["scan_type"]))
        if ref.get("host"):
            asset = str(ref["host"])
            if ref.get("port") is not None:
                asset += f":{ref['port']}"
            details.append(asset)
        if ref.get("cve"):
            details.append(str(ref["cve"]))
        if ref.get("plugin_id"):
            details.append(f"plugin {ref['plugin_id']}")
        lines.append(f"- {' | '.join(details)}")
    return lines


def build_report_content(engagement, findings, attack_paths) -> str:
    """Build a complete, portable Markdown report from stored engagement data."""
    counts = Counter(_severity(finding) for finding in findings)
    finding_summary = "\n".join(
        f"| {severity.title()} | {counts.get(severity, 0)} |"
        for severity in SEVERITY_ORDER
    )

    sections = [
        f"# {_value(engagement.name)} - Penetration Test Report",
        "",
        "Generated by Breachwright, an open-source project created by Advent Cybersecurity.",
        "",
        "## Engagement Overview",
        "",
        f"- **Client:** {_value(engagement.client_name)}",
        f"- **Scope:** {_value(engagement.scope, 'Not specified')}",
        f"- **Start date:** {_value(engagement.start_date, 'Not specified')}",
        f"- **End date:** {_value(engagement.end_date, 'Not specified')}",
        "",
        "## Executive Summary",
        "",
        (
            f"The assessment recorded {len(findings)} finding"
            f"{'' if len(findings) == 1 else 's'}. "
            f"The results include {counts.get('critical', 0)} critical, "
            f"{counts.get('high', 0)} high, {counts.get('medium', 0)} medium, "
            f"{counts.get('low', 0)} low, and {counts.get('info', 0)} "
            "informational finding(s)."
        ),
        "",
        "## Findings Summary",
        "",
        "| Severity | Count |",
        "| --- | ---: |",
        finding_summary,
        "",
        "## Detailed Findings",
        "",
    ]

    if not findings:
        sections.extend(
            [
                "No findings were recorded for this engagement.",
                "",
            ]
        )
    else:
        for index, finding in enumerate(findings, start=1):
            provenance = _provenance_lines(finding)
            sections.extend(
                [
                    f"### {index}. {_value(finding.title)}",
                    "",
                    f"- **Severity:** {_severity(finding).title()}",
                    f"- **CVSS score:** {_value(finding.cvss_score, 'Not scored')}",
                    f"- **Affected assets:** {_value(finding.affected_hosts, 'Not specified')}",
                    f"- **Retest status:** {_value(finding.retest_status, 'Not retested')}",
                    f"- **Analysis source:** {'AI-assisted, analyst reviewed' if getattr(finding, 'ai_inference', False) else 'Manual or imported'}",
                    "",
                    "#### Description",
                    "",
                    _value(finding.description),
                    "",
                    "#### Evidence",
                    "",
                    _value(finding.evidence),
                    "",
                    "#### Evidence Provenance",
                    "",
                    *(provenance or ["No scanner provenance was recorded."]),
                    "",
                    "#### Remediation",
                    "",
                    _value(finding.remediation),
                    "",
                ]
            )

    sections.extend(["## Attack Paths", ""])
    if not attack_paths:
        sections.extend(["No attack paths were recorded.", ""])
    else:
        for index, attack_path in enumerate(attack_paths, start=1):
            narrative = getattr(attack_path, "narrative", None)
            techniques = getattr(attack_path, "mitre_techniques", None) or []
            sections.extend(
                [
                    f"### {index}. {_value(attack_path.name)}",
                    "",
                    f"- **Risk level:** {_value(attack_path.risk_level, 'Not specified')}",
                    "",
                    _value(narrative or attack_path.description),
                    "",
                ]
            )
            if techniques:
                sections.extend(["#### MITRE ATT&CK Techniques", ""])
                for technique in techniques:
                    technique_id = _value(technique.get("technique_id"), "Unmapped")
                    technique_name = _value(technique.get("technique_name"), "Unnamed")
                    sections.append(f"- {technique_id}: {technique_name}")
                sections.append("")

    sections.extend(
        [
            "## Conclusion",
            "",
            (
                "Prioritize remediation according to severity and business context, "
                "then retest affected assets to confirm that corrective actions are effective."
            ),
            "",
        ]
    )
    return "\n".join(sections)
