"""Pre-built methodology checklist data.

Each methodology is a list of categorized items with descriptions,
recommended tools, techniques, and reference URLs.
"""

METHODOLOGIES = {
    "owasp_top10": {
        "name": "OWASP Top 10 (2021)",
        "description": "OWASP Top 10 Web Application Security Risks",
        "items": [
            # A01: Broken Access Control
            {"category": "A01: Broken Access Control", "item": "Test for IDOR vulnerabilities", "description": "Attempt to access resources by manipulating object references (IDs, filenames, keys) in URLs, parameters, and API calls.", "tools": "Burp Suite, OWASP ZAP, curl", "techniques": "Parameter tampering, forced browsing, horizontal/vertical privilege escalation", "reference_url": "https://owasp.org/Top10/A01_2021-Broken_Access_Control/", "order_index": 0},
            {"category": "A01: Broken Access Control", "item": "Test vertical privilege escalation", "description": "Attempt to access admin or higher-privilege functionality as a lower-privilege user.", "tools": "Burp Suite, curl", "techniques": "URL manipulation, cookie/token modification, forced browsing to admin paths", "reference_url": "https://owasp.org/Top10/A01_2021-Broken_Access_Control/", "order_index": 1},
            {"category": "A01: Broken Access Control", "item": "Test horizontal privilege escalation", "description": "Attempt to access other users' data by modifying user identifiers in requests.", "tools": "Burp Suite, Autorize plugin", "techniques": "Session token manipulation, user ID enumeration, API parameter tampering", "reference_url": "https://owasp.org/Top10/A01_2021-Broken_Access_Control/", "order_index": 2},
            {"category": "A01: Broken Access Control", "item": "Test CORS misconfiguration", "description": "Check if Cross-Origin Resource Sharing headers allow unauthorized origins to access sensitive data.", "tools": "Burp Suite, curl, browser DevTools", "techniques": "Origin header manipulation, wildcard detection, credential inclusion testing", "reference_url": "https://owasp.org/Top10/A01_2021-Broken_Access_Control/", "order_index": 3},
            {"category": "A01: Broken Access Control", "item": "Test directory traversal", "description": "Attempt to access files outside intended directories using path traversal sequences.", "tools": "Burp Suite, dotdotpwn, feroxbuster", "techniques": "Path traversal (../), URL encoding, null byte injection", "reference_url": "https://owasp.org/Top10/A01_2021-Broken_Access_Control/", "order_index": 4},
            # A02: Cryptographic Failures
            {"category": "A02: Cryptographic Failures", "item": "Check for sensitive data in transit", "description": "Verify all sensitive data transmissions use TLS 1.2+ with strong cipher suites.", "tools": "testssl.sh, sslyze, nmap ssl-enum-ciphers", "techniques": "SSL/TLS configuration analysis, certificate validation, HSTS check", "reference_url": "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/", "order_index": 10},
            {"category": "A02: Cryptographic Failures", "item": "Check for sensitive data at rest", "description": "Identify if sensitive data (passwords, PII, keys) is stored in plaintext or with weak encryption.", "tools": "Manual code review, database inspection", "techniques": "Database dump analysis, config file review, password hash identification", "reference_url": "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/", "order_index": 11},
            {"category": "A02: Cryptographic Failures", "item": "Test for weak cryptographic algorithms", "description": "Check for use of deprecated algorithms (MD5, SHA1, DES, RC4) for security-sensitive operations.", "tools": "testssl.sh, hashcat, john", "techniques": "Hash identification, cipher suite analysis, key length verification", "reference_url": "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/", "order_index": 12},
            # A03: Injection
            {"category": "A03: Injection", "item": "Test for SQL injection", "description": "Test all user inputs, parameters, headers, and cookies for SQL injection vulnerabilities.", "tools": "sqlmap, Burp Suite, OWASP ZAP", "techniques": "Error-based, blind, time-based, UNION-based SQLi; parameterized query bypass", "reference_url": "https://owasp.org/Top10/A03_2021-Injection/", "order_index": 20},
            {"category": "A03: Injection", "item": "Test for XSS (reflected, stored, DOM)", "description": "Test for cross-site scripting in all input fields, URL parameters, headers, and dynamic content.", "tools": "Burp Suite, XSStrike, dalfox", "techniques": "Reflected XSS, stored XSS, DOM-based XSS, filter bypass, encoding tricks", "reference_url": "https://owasp.org/Top10/A03_2021-Injection/", "order_index": 21},
            {"category": "A03: Injection", "item": "Test for command injection", "description": "Test parameters that may be passed to system commands for OS command injection.", "tools": "Burp Suite, commix", "techniques": "Command chaining (;, &&, ||), backtick injection, $() substitution", "reference_url": "https://owasp.org/Top10/A03_2021-Injection/", "order_index": 22},
            {"category": "A03: Injection", "item": "Test for LDAP/NoSQL/template injection", "description": "Test for injection in non-SQL backends including LDAP, MongoDB, and template engines.", "tools": "Burp Suite, NoSQLMap, tplmap", "techniques": "LDAP filter injection, MongoDB operator injection, SSTI payloads", "reference_url": "https://owasp.org/Top10/A03_2021-Injection/", "order_index": 23},
            # A04: Insecure Design
            {"category": "A04: Insecure Design", "item": "Review business logic flaws", "description": "Test for flaws in application business logic such as price manipulation, workflow bypass, and race conditions.", "tools": "Burp Suite, custom scripts", "techniques": "State manipulation, race conditions, workflow bypass, negative value testing", "reference_url": "https://owasp.org/Top10/A04_2021-Insecure_Design/", "order_index": 30},
            {"category": "A04: Insecure Design", "item": "Test rate limiting and anti-automation", "description": "Verify rate limiting on login, registration, password reset, and API endpoints.", "tools": "Burp Intruder, wfuzz, custom scripts", "techniques": "Brute force attempts, rapid request testing, CAPTCHA bypass", "reference_url": "https://owasp.org/Top10/A04_2021-Insecure_Design/", "order_index": 31},
            # A05: Security Misconfiguration
            {"category": "A05: Security Misconfiguration", "item": "Check default credentials", "description": "Test for default/common credentials on all discovered services and admin interfaces.", "tools": "Hydra, Medusa, Burp Intruder", "techniques": "Default credential lists, vendor documentation review, common password spraying", "reference_url": "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/", "order_index": 40},
            {"category": "A05: Security Misconfiguration", "item": "Check HTTP security headers", "description": "Verify presence and configuration of security headers (CSP, X-Frame-Options, HSTS, etc.).", "tools": "securityheaders.com, curl, Burp Suite", "techniques": "Header analysis, CSP bypass testing, clickjacking PoC", "reference_url": "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/", "order_index": 41},
            {"category": "A05: Security Misconfiguration", "item": "Check for verbose error messages", "description": "Verify the application does not leak stack traces, framework versions, or internal paths in error responses.", "tools": "Burp Suite, curl", "techniques": "Error triggering, invalid input, malformed requests, 404/500 analysis", "reference_url": "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/", "order_index": 42},
            {"category": "A05: Security Misconfiguration", "item": "Check for unnecessary services/features", "description": "Identify and document unnecessary open ports, enabled features, and exposed admin interfaces.", "tools": "nmap, nikto, feroxbuster", "techniques": "Port scanning, directory enumeration, feature fingerprinting", "reference_url": "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/", "order_index": 43},
            # A06: Vulnerable Components
            {"category": "A06: Vulnerable Components", "item": "Identify component versions", "description": "Enumerate all third-party libraries, frameworks, and their versions used by the application.", "tools": "Wappalyzer, retire.js, npm audit, pip-audit", "techniques": "Version fingerprinting, dependency analysis, CVE database lookup", "reference_url": "https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/", "order_index": 50},
            {"category": "A06: Vulnerable Components", "item": "Check for known CVEs", "description": "Cross-reference identified component versions against CVE databases for known vulnerabilities.", "tools": "searchsploit, vulners, NVD, Snyk", "techniques": "CVE lookup, exploit-db search, vendor advisory review", "reference_url": "https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/", "order_index": 51},
            # A07: Auth Failures
            {"category": "A07: Authentication Failures", "item": "Test password policy enforcement", "description": "Verify minimum length, complexity requirements, and common password rejection.", "tools": "Burp Suite, custom scripts", "techniques": "Weak password testing, policy boundary testing, common password lists", "reference_url": "https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/", "order_index": 60},
            {"category": "A07: Authentication Failures", "item": "Test for credential brute force", "description": "Test login endpoints for brute force resistance including account lockout and rate limiting.", "tools": "Hydra, Burp Intruder, patator", "techniques": "Password spraying, credential stuffing, lockout testing, timing analysis", "reference_url": "https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/", "order_index": 61},
            {"category": "A07: Authentication Failures", "item": "Test session management", "description": "Verify session token randomness, expiration, invalidation on logout, and secure cookie flags.", "tools": "Burp Suite, browser DevTools", "techniques": "Session fixation, token prediction, cookie analysis (Secure, HttpOnly, SameSite)", "reference_url": "https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/", "order_index": 62},
            {"category": "A07: Authentication Failures", "item": "Test MFA implementation", "description": "If MFA exists, test for bypass, replay attacks, and brute force of codes.", "tools": "Burp Suite, custom scripts", "techniques": "MFA bypass, code reuse, rate limiting on verification endpoint", "reference_url": "https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/", "order_index": 63},
            # A08: Software Integrity
            {"category": "A08: Software Integrity Failures", "item": "Check for unsigned updates/deployments", "description": "Verify that software updates, CI/CD pipelines, and deployments use integrity verification.", "tools": "Manual review", "techniques": "Update mechanism analysis, package integrity checks, CI/CD pipeline review", "reference_url": "https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/", "order_index": 70},
            {"category": "A08: Software Integrity Failures", "item": "Test for insecure deserialization", "description": "Test for unsafe deserialization of user-controlled data that could lead to RCE.", "tools": "ysoserial, Burp Java Deserialization Scanner", "techniques": "Serialized object manipulation, gadget chain exploitation, type confusion", "reference_url": "https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/", "order_index": 71},
            # A09: Logging Failures
            {"category": "A09: Logging & Monitoring Failures", "item": "Verify security event logging", "description": "Check that login attempts, access control failures, and input validation failures are logged.", "tools": "Manual review, log analysis", "techniques": "Log review, failed login testing, access violation triggering", "reference_url": "https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/", "order_index": 80},
            # A10: SSRF
            {"category": "A10: SSRF", "item": "Test for SSRF vulnerabilities", "description": "Test parameters that accept URLs or IP addresses for server-side request forgery.", "tools": "Burp Suite, SSRFmap, Collaborator", "techniques": "Internal network scanning, cloud metadata access (169.254.169.254), protocol smuggling", "reference_url": "https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/", "order_index": 90},
        ],
    },
    "owasp_api_top10": {
        "name": "OWASP API Security Top 10 (2023)",
        "description": "API-focused coverage for the current OWASP API Security Top 10 edition",
        "items": [
            {"category": "API1:2023 Broken Object Level Authorization", "item": "Test object identifiers across identities", "description": "Replay object-based requests with identifiers owned by other users, tenants, and roles, including nested and bulk object operations.", "tools": "Burp Suite, curl, jq", "techniques": "Identifier substitution, cross-tenant access, bulk object authorization", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 0},
            {"category": "API2:2023 Broken Authentication", "item": "Test every authentication and token lifecycle flow", "description": "Assess sign-in, recovery, refresh, revocation, logout, API keys, and machine identities for bypass, replay, weak validation, and enumeration.", "tools": "Burp Suite, curl, jwt-tool", "techniques": "Token replay, claim manipulation, credential enumeration, refresh-token rotation", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 10},
            {"category": "API3:2023 Broken Object Property Level Authorization", "item": "Test readable and writable object properties", "description": "Compare responses and update payloads across roles to identify excessive data exposure, hidden-field modification, and unsafe mass assignment.", "tools": "Burp Suite, jq, custom scripts", "techniques": "Response diffing, property injection, field-level authorization testing", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 20},
            {"category": "API4:2023 Unrestricted Resource Consumption", "item": "Exercise resource and cost boundaries", "description": "Test request size, pagination, batch operations, uploads, GraphQL depth, concurrency, and third-party cost triggers using authorized safe limits.", "tools": "Burp Intruder, k6, curl", "techniques": "Rate-limit testing, payload amplification, pagination abuse, concurrency testing", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 30},
            {"category": "API5:2023 Broken Function Level Authorization", "item": "Enumerate privileged functions and alternate methods", "description": "Attempt administrative and higher-privilege operations from lower-privilege identities using alternate paths, versions, verbs, and content types.", "tools": "Burp Suite, ffuf, curl", "techniques": "Forced browsing, HTTP verb tampering, role matrix testing", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 40},
            {"category": "API6:2023 Unrestricted Access to Sensitive Business Flows", "item": "Test automation resistance in sensitive workflows", "description": "Assess high-value flows such as purchasing, reservations, invitations, referrals, and account actions for replay, race conditions, and abusive automation.", "tools": "Burp Suite, Turbo Intruder, custom scripts", "techniques": "Workflow replay, race testing, anti-automation bypass, business-limit abuse", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 50},
            {"category": "API7:2023 Server Side Request Forgery", "item": "Test server-side URL and callback handling", "description": "Evaluate webhooks, importers, previews, fetchers, and callback URLs for access to internal services, cloud metadata, alternate schemes, and redirect bypasses.", "tools": "Burp Collaborator, interactsh, curl", "techniques": "Internal-address targeting, redirect chains, DNS rebinding checks, scheme validation", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 60},
            {"category": "API8:2023 Security Misconfiguration", "item": "Review API transport, middleware, and error behavior", "description": "Check TLS, CORS, allowed methods, content types, debug endpoints, error detail, caching, security headers, and default credentials across every deployed environment.", "tools": "Burp Suite, testssl.sh, curl", "techniques": "Configuration diffing, malformed requests, origin testing, method enumeration", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 70},
            {"category": "API9:2023 Improper Inventory Management", "item": "Reconcile documented and deployed API inventory", "description": "Discover hosts, versions, routes, schemas, and deprecated endpoints, then compare them with ownership, environment, and retirement records.", "tools": "Amass, httpx, katana, Swagger tools", "techniques": "Version discovery, schema enumeration, shadow and zombie API identification", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 80},
            {"category": "API10:2023 Unsafe Consumption of APIs", "item": "Test trust boundaries around downstream APIs", "description": "Verify data from third-party and internal APIs is validated, constrained, and safely processed across redirects, timeouts, parsers, and error paths.", "tools": "Burp Suite, mock server, mitmproxy", "techniques": "Downstream response tampering, redirect testing, parser boundary testing, timeout and failure injection", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 90},
        ],
    },
    "ptes": {
        "name": "PTES (Penetration Testing Execution Standard)",
        "description": "Comprehensive penetration testing methodology covering all phases",
        "items": [
            # Pre-engagement
            {"category": "Pre-Engagement", "item": "Define scope and rules of engagement", "description": "Document target systems, IP ranges, testing windows, emergency contacts, and out-of-scope items.", "tools": "Documentation templates", "techniques": "Scope definition, legal review, emergency procedures", "reference_url": "http://www.pentest-standard.org/index.php/Pre-engagement", "order_index": 0},
            {"category": "Pre-Engagement", "item": "Obtain written authorization", "description": "Ensure signed authorization (Rules of Engagement, Statement of Work) covering all testing activities.", "tools": "Legal templates", "techniques": "Contract review, scope validation, point-of-contact confirmation", "reference_url": "http://www.pentest-standard.org/index.php/Pre-engagement", "order_index": 1},
            # Intelligence Gathering
            {"category": "Intelligence Gathering", "item": "Passive reconnaissance", "description": "Gather information without directly interacting with target systems.", "tools": "theHarvester, Shodan, Maltego, Google dorks", "techniques": "OSINT, DNS enumeration, social media profiling, job posting analysis", "reference_url": "http://www.pentest-standard.org/index.php/Intelligence_Gathering", "order_index": 10},
            {"category": "Intelligence Gathering", "item": "Active reconnaissance", "description": "Directly interact with targets to enumerate services, versions, and configurations.", "tools": "nmap, subfinder, httpx, dig, whois", "techniques": "Port scanning, service fingerprinting, DNS zone transfers, banner grabbing", "reference_url": "http://www.pentest-standard.org/index.php/Intelligence_Gathering", "order_index": 11},
            {"category": "Intelligence Gathering", "item": "Identify external footprint", "description": "Map all externally accessible systems, subdomains, and services.", "tools": "subfinder, amass, censys, crt.sh", "techniques": "Subdomain enumeration, certificate transparency logs, IP range identification", "reference_url": "http://www.pentest-standard.org/index.php/Intelligence_Gathering", "order_index": 12},
            # Threat Modeling
            {"category": "Threat Modeling", "item": "Identify high-value assets", "description": "Determine which systems and data are most valuable to the organization.", "tools": "Documentation, interviews", "techniques": "Asset classification, data flow mapping, crown jewel analysis", "reference_url": "http://www.pentest-standard.org/index.php/Threat_Modeling", "order_index": 20},
            {"category": "Threat Modeling", "item": "Map attack surface", "description": "Document all potential entry points and attack vectors based on gathered intelligence.", "tools": "Manual analysis, attack surface mapping tools", "techniques": "Entry point identification, trust boundary analysis, threat actor profiling", "reference_url": "http://www.pentest-standard.org/index.php/Threat_Modeling", "order_index": 21},
            # Vulnerability Analysis
            {"category": "Vulnerability Analysis", "item": "Automated vulnerability scanning", "description": "Run vulnerability scanners against in-scope targets to identify known vulnerabilities.", "tools": "Nessus, OpenVAS, Nuclei, nikto", "techniques": "Credentialed and non-credentialed scanning, plugin selection, false positive validation", "reference_url": "http://www.pentest-standard.org/index.php/Vulnerability_Analysis", "order_index": 30},
            {"category": "Vulnerability Analysis", "item": "Manual vulnerability analysis", "description": "Manually test for vulnerabilities that automated scanners miss.", "tools": "Burp Suite, manual testing", "techniques": "Logic flaw testing, authentication bypass, input validation testing", "reference_url": "http://www.pentest-standard.org/index.php/Vulnerability_Analysis", "order_index": 31},
            {"category": "Vulnerability Analysis", "item": "Validate and prioritize findings", "description": "Confirm vulnerabilities are exploitable and prioritize by risk to the organization.", "tools": "Manual validation, PoC development", "techniques": "Exploit validation, CVSS scoring, business impact assessment", "reference_url": "http://www.pentest-standard.org/index.php/Vulnerability_Analysis", "order_index": 32},
            # Exploitation
            {"category": "Exploitation", "item": "Exploit confirmed vulnerabilities", "description": "Attempt exploitation of validated vulnerabilities to demonstrate impact.", "tools": "Metasploit, manual exploits, custom scripts", "techniques": "Public exploit modification, custom payload development, evasion techniques", "reference_url": "http://www.pentest-standard.org/index.php/Exploitation", "order_index": 40},
            {"category": "Exploitation", "item": "Establish foothold", "description": "Gain initial access to target systems through exploited vulnerabilities.", "tools": "Metasploit, Cobalt Strike, Sliver, reverse shells", "techniques": "Reverse shells, web shells, implant deployment, persistence mechanisms", "reference_url": "http://www.pentest-standard.org/index.php/Exploitation", "order_index": 41},
            # Post-Exploitation
            {"category": "Post-Exploitation", "item": "Privilege escalation", "description": "Attempt to escalate from initial access to administrative or root privileges.", "tools": "LinPEAS, WinPEAS, PowerUp, SharpUp", "techniques": "Kernel exploits, misconfigurations, credential harvesting, token manipulation", "reference_url": "http://www.pentest-standard.org/index.php/Post_Exploitation", "order_index": 50},
            {"category": "Post-Exploitation", "item": "Lateral movement", "description": "Move from compromised systems to other systems in the network.", "tools": "CrackMapExec, Impacket, PsExec, Evil-WinRM", "techniques": "Pass-the-hash, pass-the-ticket, RDP, WMI, SMB relay", "reference_url": "http://www.pentest-standard.org/index.php/Post_Exploitation", "order_index": 51},
            {"category": "Post-Exploitation", "item": "Data exfiltration demonstration", "description": "Demonstrate ability to access and exfiltrate sensitive data (with appropriate authorization).", "tools": "Custom scripts, built-in OS tools", "techniques": "Database dumping, file collection, credential extraction", "reference_url": "http://www.pentest-standard.org/index.php/Post_Exploitation", "order_index": 52},
            {"category": "Post-Exploitation", "item": "Active Directory attacks", "description": "If AD is in scope, test for Kerberoasting, AS-REP roasting, delegation abuse, and ACL attacks.", "tools": "BloodHound, Rubeus, Impacket, SharpHound", "techniques": "Kerberoasting, DCSync, Golden/Silver tickets, ACL abuse", "reference_url": "http://www.pentest-standard.org/index.php/Post_Exploitation", "order_index": 53},
            # Reporting
            {"category": "Reporting", "item": "Document all findings with evidence", "description": "Create detailed documentation of each finding including screenshots, commands, and impact.", "tools": "Breachwright, screenshot tools", "techniques": "Evidence collection, reproduction steps, impact assessment", "reference_url": "http://www.pentest-standard.org/index.php/Reporting", "order_index": 60},
            {"category": "Reporting", "item": "Generate client report", "description": "Produce professional report with executive summary, detailed findings, and remediation guidance.", "tools": "Breachwright DOCX generation", "techniques": "Risk-based prioritization, clear remediation steps, executive-level summary", "reference_url": "http://www.pentest-standard.org/index.php/Reporting", "order_index": 61},
            {"category": "Reporting", "item": "Conduct debrief with client", "description": "Present findings to technical and management stakeholders with Q&A.", "tools": "Presentation slides, report walkthrough", "techniques": "Executive summary presentation, technical deep-dive, remediation planning", "reference_url": "http://www.pentest-standard.org/index.php/Reporting", "order_index": 62},
        ],
    },
    "nist_800_115": {
        "name": "NIST SP 800-115",
        "description": "Technical Guide to Information Security Testing and Assessment",
        "items": [
            # Planning
            {"category": "Planning", "item": "Define assessment objectives", "description": "Establish clear objectives aligned with organizational security goals.", "tools": "Documentation", "techniques": "Goal setting, scope definition, stakeholder alignment", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 0},
            {"category": "Planning", "item": "Define rules of engagement", "description": "Document testing boundaries, timing, notification procedures, and escalation paths.", "tools": "Templates, legal review", "techniques": "ROE development, communication planning, incident response coordination", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 1},
            # Discovery
            {"category": "Discovery", "item": "Network discovery and mapping", "description": "Identify live hosts, network topology, and routing within the target environment.", "tools": "nmap, netdiscover, arp-scan", "techniques": "Ping sweeps, ARP scanning, traceroute, network mapping", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 10},
            {"category": "Discovery", "item": "Port and service enumeration", "description": "Identify open ports and running services on discovered hosts.", "tools": "nmap, masscan, rustscan", "techniques": "TCP/UDP scanning, version detection, script scanning", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 11},
            {"category": "Discovery", "item": "OS and service fingerprinting", "description": "Determine operating systems and specific service versions on target hosts.", "tools": "nmap, p0f, Wappalyzer", "techniques": "TCP/IP fingerprinting, banner grabbing, HTTP header analysis", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 12},
            # Vulnerability Assessment
            {"category": "Vulnerability Assessment", "item": "Network vulnerability scanning", "description": "Scan network services for known vulnerabilities using automated tools.", "tools": "Nessus, OpenVAS, Qualys", "techniques": "Credentialed scanning, plugin-based detection, compliance checks", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 20},
            {"category": "Vulnerability Assessment", "item": "Web application testing", "description": "Test web applications for OWASP Top 10 and other common vulnerabilities.", "tools": "Burp Suite, OWASP ZAP, nikto", "techniques": "Injection testing, authentication testing, session management analysis", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 21},
            {"category": "Vulnerability Assessment", "item": "Wireless security assessment", "description": "If in scope, test wireless networks for encryption weaknesses and rogue access points.", "tools": "aircrack-ng, kismet, wifite", "techniques": "WPA handshake capture, deauth attacks, rogue AP detection", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 22},
            {"category": "Vulnerability Assessment", "item": "Social engineering assessment", "description": "If in scope, test human element through phishing, pretexting, or physical access attempts.", "tools": "Gophish, SET, custom phishing templates", "techniques": "Phishing campaigns, pretexting calls, physical security testing", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 23},
            # Penetration Testing
            {"category": "Penetration Testing", "item": "Exploit identified vulnerabilities", "description": "Attempt controlled exploitation to determine real-world impact of vulnerabilities.", "tools": "Metasploit, manual exploits, custom scripts", "techniques": "Exploit development, payload customization, evasion", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 30},
            {"category": "Penetration Testing", "item": "Post-exploitation assessment", "description": "Assess the impact of successful exploitation including data access and lateral movement.", "tools": "Meterpreter, Cobalt Strike, Impacket", "techniques": "Privilege escalation, credential harvesting, pivoting, data access", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 31},
            # Analysis & Reporting
            {"category": "Analysis & Reporting", "item": "Analyze and correlate findings", "description": "Correlate findings across scanning, testing, and exploitation to determine overall risk.", "tools": "Breachwright, manual analysis", "techniques": "Risk scoring, attack chain mapping, business impact assessment", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 40},
            {"category": "Analysis & Reporting", "item": "Develop remediation roadmap", "description": "Create prioritized remediation plan with short-term fixes and long-term improvements.", "tools": "Breachwright report generation", "techniques": "Risk-based prioritization, quick wins identification, strategic planning", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 41},
        ],
    },
    "network_pentest": {
        "name": "Network Penetration Test",
        "description": "Standard network penetration testing checklist for internal/external assessments",
        "items": [
            {"category": "Reconnaissance", "item": "DNS enumeration", "description": "Enumerate DNS records, zone transfers, and subdomain discovery.", "tools": "dig, dnsenum, subfinder, amass", "techniques": "Zone transfer (AXFR), subdomain brute force, reverse DNS", "reference_url": "", "order_index": 0},
            {"category": "Reconnaissance", "item": "WHOIS and ASN lookup", "description": "Identify domain registration, IP ranges, and autonomous system information.", "tools": "whois, bgp.he.net, ARIN", "techniques": "IP range identification, registrant information, network ownership", "reference_url": "", "order_index": 1},
            {"category": "Scanning", "item": "Full TCP port scan", "description": "Scan all 65535 TCP ports on target hosts.", "tools": "nmap, masscan, rustscan", "techniques": "SYN scan, connect scan, version detection", "reference_url": "", "order_index": 10},
            {"category": "Scanning", "item": "UDP port scan (top 100)", "description": "Scan common UDP ports for services like DNS, SNMP, NTP.", "tools": "nmap -sU", "techniques": "UDP scanning, SNMP enumeration, DNS recursion testing", "reference_url": "", "order_index": 11},
            {"category": "Scanning", "item": "Service version detection", "description": "Identify exact versions of running services for CVE lookup.", "tools": "nmap -sV, banner grabbing", "techniques": "Version fingerprinting, script scanning, manual banner analysis", "reference_url": "", "order_index": 12},
            {"category": "Enumeration", "item": "SMB enumeration", "description": "Enumerate SMB shares, users, policies, and test for null sessions.", "tools": "enum4linux, CrackMapExec, smbclient", "techniques": "Null session testing, share enumeration, user listing, password policy", "reference_url": "", "order_index": 20},
            {"category": "Enumeration", "item": "SNMP enumeration", "description": "Test for default community strings and enumerate SNMP data.", "tools": "snmpwalk, onesixtyone, snmp-check", "techniques": "Community string brute force, MIB walking, system info extraction", "reference_url": "", "order_index": 21},
            {"category": "Enumeration", "item": "LDAP enumeration", "description": "Enumerate LDAP directory for users, groups, and organizational information.", "tools": "ldapsearch, windapsearch, ad-ldap-enum", "techniques": "Anonymous bind testing, user enumeration, group membership mapping", "reference_url": "", "order_index": 22},
            {"category": "Enumeration", "item": "Web service enumeration", "description": "Enumerate web applications, directories, and technologies.", "tools": "feroxbuster, nikto, Wappalyzer", "techniques": "Directory brute force, technology fingerprinting, virtual host enumeration", "reference_url": "", "order_index": 23},
            {"category": "Exploitation", "item": "Test for known CVEs", "description": "Attempt exploitation of identified CVEs on running services.", "tools": "Metasploit, searchsploit, custom PoCs", "techniques": "CVE exploitation, version-specific attacks, proof of concept validation", "reference_url": "", "order_index": 30},
            {"category": "Exploitation", "item": "Password attacks", "description": "Test for weak and default passwords on discovered services.", "tools": "Hydra, CrackMapExec, medusa", "techniques": "Password spraying, brute force, default credentials, credential stuffing", "reference_url": "", "order_index": 31},
            {"category": "Exploitation", "item": "Man-in-the-middle testing", "description": "Test for MITM vulnerabilities such as LLMNR/NBT-NS poisoning and ARP spoofing.", "tools": "Responder, mitm6, Bettercap", "techniques": "LLMNR poisoning, NTLM relay, DNS spoofing, ARP poisoning", "reference_url": "", "order_index": 32},
            {"category": "Post-Exploitation", "item": "Credential harvesting", "description": "Extract credentials from compromised systems (SAM, LSASS, cached creds).", "tools": "mimikatz, secretsdump.py, LaZagne", "techniques": "LSASS dumping, SAM extraction, cached credential recovery, DPAPI", "reference_url": "", "order_index": 40},
            {"category": "Post-Exploitation", "item": "Lateral movement", "description": "Move to additional systems using harvested credentials or techniques.", "tools": "CrackMapExec, PsExec, Evil-WinRM, Impacket", "techniques": "Pass-the-hash, pass-the-ticket, WMI execution, RDP", "reference_url": "", "order_index": 41},
            {"category": "Post-Exploitation", "item": "Domain privilege escalation", "description": "Escalate to Domain Admin through AD attack paths.", "tools": "BloodHound, Rubeus, Impacket", "techniques": "Kerberoasting, AS-REP roasting, ACL abuse, delegation attacks", "reference_url": "", "order_index": 42},
        ],
    },
}


def get_methodology_items(methodology_key: str) -> list[dict]:
    """Get checklist items for a methodology."""
    meth = METHODOLOGIES.get(methodology_key)
    if not meth:
        return []
    return meth["items"]


def get_available_methodologies() -> dict:
    """List available methodologies with metadata."""
    return {
        key: {"name": m["name"], "description": m["description"], "item_count": len(m["items"])}
        for key, m in METHODOLOGIES.items()
    }
