"""Pre-built methodology checklist data.

Each methodology is a list of categorized items with descriptions,
recommended tools, techniques, and reference URLs.
"""

METHODOLOGIES = {
    "owasp_top10": {
        "name": "OWASP Top 10 (2025)",
        "description": "Baseline web coverage aligned with OWASP Top 10:2025; not a complete testing standard",
        "items": [
            # A01:2025 Broken Access Control
            {"category": "A01:2025 Broken Access Control", "item": "Test for IDOR vulnerabilities", "description": "Attempt to access resources by manipulating object references in URLs, parameters, and API calls.", "tools": "Burp Suite, OWASP ZAP, curl", "techniques": "Parameter tampering, forced browsing, horizontal and vertical privilege escalation", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 0},
            {"category": "A01:2025 Broken Access Control", "item": "Test vertical privilege escalation", "description": "Attempt to access higher-privilege functionality as a lower-privilege identity.", "tools": "Burp Suite, curl", "techniques": "URL manipulation, cookie and token modification, forced browsing", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 1},
            {"category": "A01:2025 Broken Access Control", "item": "Test horizontal privilege escalation", "description": "Attempt to access other users' or tenants' data by modifying identifiers in requests.", "tools": "Burp Suite, Autorize", "techniques": "Session comparison, identifier enumeration, parameter tampering", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 2},
            {"category": "A01:2025 Broken Access Control", "item": "Test CORS and forced browsing controls", "description": "Check cross-origin policy, unlinked routes, alternate methods, and privileged endpoints for unauthorized access.", "tools": "Burp Suite, curl, browser DevTools", "techniques": "Origin manipulation, route discovery, method tampering", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 3},
            {"category": "A01:2025 Broken Access Control", "item": "Test path traversal and file authorization", "description": "Attempt to reach files outside intended directories and retrieve protected objects through alternate paths.", "tools": "Burp Suite, dotdotpwn, feroxbuster", "techniques": "Traversal sequences, encoding variants, alternate path testing", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 4},
            {"category": "A01:2025 Broken Access Control", "item": "Test server-side request forgery", "description": "Test URL, callback, import, and fetch features for unauthorized access to internal services and cloud metadata.", "tools": "Burp Collaborator, interactsh, SSRFmap", "techniques": "Internal addressing, redirect chains, alternate schemes, DNS rebinding checks", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 5},
            # A02:2025 Security Misconfiguration
            {"category": "A02:2025 Security Misconfiguration", "item": "Check default credentials and sample content", "description": "Test discovered services, administration interfaces, sample applications, and documentation for unsafe defaults.", "tools": "Burp Suite, nmap, vendor documentation", "techniques": "Default credential review, sample-route discovery, environment comparison", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 10},
            {"category": "A02:2025 Security Misconfiguration", "item": "Check HTTP security controls", "description": "Review TLS, security headers, CORS, methods, caching, and cookie configuration across deployed environments.", "tools": "testssl.sh, curl, Burp Suite", "techniques": "Header analysis, origin testing, method enumeration, configuration diffing", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 11},
            {"category": "A02:2025 Security Misconfiguration", "item": "Check exposed services and management surfaces", "description": "Identify unnecessary ports, features, debug routes, cloud storage, and administration interfaces.", "tools": "nmap, nikto, feroxbuster", "techniques": "Port scanning, directory enumeration, service and feature fingerprinting", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 12},
            # A03:2025 Software Supply Chain Failures
            {"category": "A03:2025 Software Supply Chain Failures", "item": "Inventory components and dependency sources", "description": "Enumerate application, client, container, and build dependencies with versions, origin, and ownership.", "tools": "SBOM tools, Wappalyzer, retire.js, package audits", "techniques": "Dependency inventory, version fingerprinting, provenance review", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 20},
            {"category": "A03:2025 Software Supply Chain Failures", "item": "Check dependencies for known vulnerabilities", "description": "Compare identified components with vendor advisories and vulnerability databases, including transitive dependencies.", "tools": "pip-audit, npm audit, osv-scanner, vendor advisories", "techniques": "CVE review, reachability analysis, exploitability validation", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 21},
            {"category": "A03:2025 Software Supply Chain Failures", "item": "Review build, update, and distribution trust", "description": "Assess dependency pinning, artifact sources, build access, update channels, and release provenance for compromise paths.", "tools": "Manual review, CI/CD logs, SBOM and signing tools", "techniques": "Pipeline trust review, dependency confusion checks, artifact provenance validation", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 22},
            # A04:2025 Cryptographic Failures
            {"category": "A04:2025 Cryptographic Failures", "item": "Check sensitive data in transit", "description": "Verify sensitive data uses current TLS, trusted certificates, and appropriate transport protections.", "tools": "testssl.sh, sslyze, nmap ssl-enum-ciphers", "techniques": "TLS analysis, certificate validation, HSTS review", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 30},
            {"category": "A04:2025 Cryptographic Failures", "item": "Check sensitive data at rest", "description": "Identify plaintext or weakly protected credentials, personal data, tokens, and keys.", "tools": "Manual review, database inspection, secret scanners", "techniques": "Storage review, key handling review, password hash identification", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 31},
            {"category": "A04:2025 Cryptographic Failures", "item": "Test cryptographic algorithm and key use", "description": "Check algorithms, modes, randomness, key lengths, rotation, and certificate validation for security-sensitive operations.", "tools": "testssl.sh, code review, cryptographic test tools", "techniques": "Algorithm review, entropy checks, key lifecycle testing", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 32},
            # A05:2025 Injection
            {"category": "A05:2025 Injection", "item": "Test SQL and query injection", "description": "Test parameters, headers, cookies, and structured inputs for SQL and other data-store injection.", "tools": "sqlmap, Burp Suite, OWASP ZAP", "techniques": "Error-based, blind, time-based, UNION, NoSQL, and ORM injection", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 40},
            {"category": "A05:2025 Injection", "item": "Test cross-site scripting", "description": "Test reflected, stored, and DOM-controlled data across HTML, JavaScript, URL, and template contexts.", "tools": "Burp Suite, XSStrike, dalfox", "techniques": "Context-aware payloads, encoding variants, DOM source and sink review", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 41},
            {"category": "A05:2025 Injection", "item": "Test command and expression injection", "description": "Test data reaching operating-system commands, interpreters, templates, and expression languages.", "tools": "Burp Suite, commix, tplmap", "techniques": "Command separators, argument injection, SSTI, expression-language injection", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 42},
            {"category": "A05:2025 Injection", "item": "Test LDAP, XML, and parser injection", "description": "Exercise directory filters, XML parsers, path expressions, and other interpreters with controlled malformed input.", "tools": "Burp Suite, custom payloads", "techniques": "LDAP injection, XPath injection, XXE, parser boundary testing", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 43},
            # A06:2025 Insecure Design
            {"category": "A06:2025 Insecure Design", "item": "Review business logic and trust boundaries", "description": "Test pricing, workflow, state, tenant, and approval assumptions for abuse that input validation cannot prevent.", "tools": "Burp Suite, threat models, custom scripts", "techniques": "Workflow bypass, state manipulation, race testing, negative-value testing", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 50},
            {"category": "A06:2025 Insecure Design", "item": "Test business limits and anti-automation design", "description": "Verify sensitive actions have effective business limits, replay resistance, and abuse controls.", "tools": "Burp Intruder, Turbo Intruder, custom scripts", "techniques": "Rapid replay, concurrency testing, quota and anti-automation bypass", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 51},
            # A07:2025 Authentication Failures
            {"category": "A07:2025 Authentication Failures", "item": "Test credential and recovery policy", "description": "Assess password, registration, recovery, and enumeration controls against current organizational requirements.", "tools": "Burp Suite, custom scripts", "techniques": "Policy boundary testing, recovery abuse, username enumeration", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 60},
            {"category": "A07:2025 Authentication Failures", "item": "Test brute-force and credential-stuffing resistance", "description": "Exercise sign-in and recovery endpoints using authorized safe rates to verify throttling and detection.", "tools": "Burp Intruder, Hydra, custom scripts", "techniques": "Password spraying, credential stuffing, rate-limit testing", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 61},
            {"category": "A07:2025 Authentication Failures", "item": "Test session and token lifecycle", "description": "Verify token randomness, scope, renewal, expiration, logout invalidation, replay resistance, and cookie controls.", "tools": "Burp Suite, browser DevTools, jwt-tool", "techniques": "Session fixation, token replay, claim manipulation, cookie review", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 62},
            {"category": "A07:2025 Authentication Failures", "item": "Test multifactor authentication", "description": "Where present, test enrollment, recovery, step-up, code reuse, rate limits, and bypass paths.", "tools": "Burp Suite, custom scripts", "techniques": "MFA workflow bypass, replay, recovery-path testing", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 63},
            # A08:2025 Software or Data Integrity Failures
            {"category": "A08:2025 Software or Data Integrity Failures", "item": "Test trusted data and update integrity", "description": "Verify application updates, plugins, serialized state, and security-sensitive data cross trust boundaries with integrity validation.", "tools": "Manual review, update inspection", "techniques": "Signature verification, tampering tests, trust-boundary review", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 70},
            {"category": "A08:2025 Software or Data Integrity Failures", "item": "Test unsafe deserialization and object binding", "description": "Test user-controlled serialized objects and polymorphic data for type confusion, gadget execution, and unsafe state changes.", "tools": "ysoserial, Burp extensions, custom payloads", "techniques": "Object manipulation, gadget chains, type confusion", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 71},
            # A09:2025 Security Logging and Alerting Failures
            {"category": "A09:2025 Security Logging and Alerting Failures", "item": "Verify security logging and actionable alerting", "description": "Confirm authentication, authorization, validation, administration, and high-risk business events are logged with useful context and tested alerts.", "tools": "Manual review, log and alert testing", "techniques": "Event triggering, tamper review, alert verification, sensitive-data checks", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 80},
            # A10:2025 Mishandling of Exceptional Conditions
            {"category": "A10:2025 Mishandling of Exceptional Conditions", "item": "Test error responses for disclosure", "description": "Trigger malformed, missing, and unexpected inputs and verify responses do not disclose stack traces, secrets, internal paths, or implementation details.", "tools": "Burp Suite, curl", "techniques": "Malformed requests, missing parameters, boundary values, 4xx and 5xx analysis", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 90},
            {"category": "A10:2025 Mishandling of Exceptional Conditions", "item": "Test fail-safe authorization and transaction behavior", "description": "Verify timeouts, downstream failures, partial operations, and insufficient privileges fail closed without bypassing controls or corrupting state.", "tools": "Burp Suite, mock services, fault injection", "techniques": "Fail-open testing, timeout injection, partial transaction and rollback testing", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 91},
            {"category": "A10:2025 Mishandling of Exceptional Conditions", "item": "Test resource and state boundaries", "description": "Exercise oversized, concurrent, repeated, and out-of-order operations at authorized limits to identify crashes, unsafe defaults, and inconsistent state.", "tools": "Burp Intruder, Turbo Intruder, custom scripts", "techniques": "Boundary testing, concurrency, sequence manipulation, resource exhaustion checks", "reference_url": "https://owasp.org/Top10/2025/", "order_index": 92},
        ],
    },
    "owasp_api_top10": {
        "name": "OWASP API Security Top 10 (2023)",
        "description": "API-focused coverage for the current OWASP API Security Top 10 edition",
        "items": [
            {"category": "API1:2023 Broken Object Level Authorization", "item": "Test object identifiers across identities", "description": "Replay object-based requests with identifiers owned by other users, tenants, and roles, including nested and bulk object operations.", "tools": "Burp Suite, curl, jq", "techniques": "Identifier substitution, cross-tenant access, bulk object authorization", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 0},
            {"category": "API2:2023 Broken Authentication", "item": "Test every authentication and token lifecycle flow", "description": "Assess sign-in, recovery, refresh, revocation, logout, API keys, and machine identities for bypass, replay, weak validation, and enumeration.", "tools": "Burp Suite, curl, jwt-tool", "techniques": "Token replay, claim manipulation, credential enumeration, refresh-token rotation", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 10},
            {"category": "API3:2023 Broken Object Property Level Authorization", "item": "Test readable and writable object properties", "description": "Compare responses and update payloads across roles to identify excessive data exposure, hidden-field modification, and unsafe mass assignment.", "tools": "Burp Suite, jq, custom scripts", "techniques": "Response diffing, property injection, field-level authorization testing", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 20},
            {"category": "API4:2023 Unrestricted Resource Consumption", "item": "Exercise resource and cost boundaries", "description": "Test request size, pagination, batch operations, uploads, GraphQL depth, concurrency, and third-party cost triggers using authorized safe limits.", "tools": "Burp Intruder, k6, curl", "techniques": "Rate-limit testing, payload amplification, pagination abuse, concurrency testing", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 30},
            {"category": "API5:2023 Broken Function Level Authorization", "item": "Enumerate privileged functions and alternate methods", "description": "Attempt administrative and higher-privilege operations from lower-privilege identities using alternate paths, versions, verbs, and content types.", "tools": "Burp Suite, ffuf, curl", "techniques": "Forced browsing, HTTP verb tampering, role matrix testing", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 40},
            {"category": "API6:2023 Unrestricted Access to Sensitive Business Flows", "item": "Test automation resistance in sensitive workflows", "description": "Assess high-value flows such as purchasing, reservations, invitations, referrals, and account actions for replay, race conditions, and abusive automation.", "tools": "Burp Suite, Turbo Intruder, custom scripts", "techniques": "Workflow replay, race testing, anti-automation bypass, business-limit abuse", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 50},
            {"category": "API7:2023 Server Side Request Forgery", "item": "Test server-side URL and callback handling", "description": "Evaluate webhooks, importers, previews, fetchers, and callback URLs for access to internal services, cloud metadata, alternate schemes, and redirect bypasses.", "tools": "Burp Collaborator, interactsh, curl", "techniques": "Internal-address targeting, redirect chains, DNS rebinding checks, scheme validation", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 60},
            {"category": "API8:2023 Security Misconfiguration", "item": "Review API transport, middleware, and error behavior", "description": "Check TLS, CORS, allowed methods, content types, debug endpoints, error detail, caching, security headers, and default credentials across every deployed environment.", "tools": "Burp Suite, testssl.sh, curl", "techniques": "Configuration diffing, malformed requests, origin testing, method enumeration", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 70},
            {"category": "API9:2023 Improper Inventory Management", "item": "Reconcile documented and deployed API inventory", "description": "Discover hosts, versions, routes, schemas, and deprecated endpoints, then compare them with ownership, environment, and retirement records.", "tools": "Amass, httpx, katana, Swagger tools", "techniques": "Version discovery, schema enumeration, shadow and zombie API identification", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 80},
            {"category": "API10:2023 Unsafe Consumption of APIs", "item": "Test trust boundaries around downstream APIs", "description": "Verify data from third-party and internal APIs is validated, constrained, and safely processed across redirects, timeouts, parsers, and error paths.", "tools": "Burp Suite, mock server, mitmproxy", "techniques": "Downstream response tampering, redirect testing, parser boundary testing, timeout and failure injection", "reference_url": "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "order_index": 90},
        ],
    },
    "ptes": {
        "name": "PTES (Penetration Testing Execution Standard)",
        "description": "Comprehensive penetration testing methodology covering all phases",
        "items": [
            # Pre-engagement
            {"category": "Pre-Engagement", "item": "Define scope and rules of engagement", "description": "Document target systems, IP ranges, testing windows, emergency contacts, and out-of-scope items.", "tools": "Documentation templates", "techniques": "Scope definition, legal review, emergency procedures", "reference_url": "http://www.pentest-standard.org/index.php/Pre-engagement", "order_index": 0},
            {"category": "Pre-Engagement", "item": "Obtain written authorization", "description": "Ensure signed authorization (Rules of Engagement, Statement of Work) covering all testing activities.", "tools": "Legal templates", "techniques": "Contract review, scope validation, point-of-contact confirmation", "reference_url": "http://www.pentest-standard.org/index.php/Pre-engagement", "order_index": 1},
            # Intelligence Gathering
            {"category": "Intelligence Gathering", "item": "Passive reconnaissance", "description": "Gather information without directly interacting with target systems.", "tools": "theHarvester, Shodan, Maltego, Google dorks", "techniques": "OSINT, DNS enumeration, social media profiling, job posting analysis", "reference_url": "http://www.pentest-standard.org/index.php/Intelligence_Gathering", "order_index": 10},
            {"category": "Intelligence Gathering", "item": "Active reconnaissance", "description": "Directly interact with targets to enumerate services, versions, and configurations.", "tools": "nmap, subfinder, httpx, dig, whois", "techniques": "Port scanning, service fingerprinting, DNS zone transfers, banner grabbing", "reference_url": "http://www.pentest-standard.org/index.php/Intelligence_Gathering", "order_index": 11},
            {"category": "Intelligence Gathering", "item": "Identify external footprint", "description": "Map all externally accessible systems, subdomains, and services.", "tools": "subfinder, amass, censys, crt.sh", "techniques": "Subdomain enumeration, certificate transparency logs, IP range identification", "reference_url": "http://www.pentest-standard.org/index.php/Intelligence_Gathering", "order_index": 12},
            # Threat Modeling
            {"category": "Threat Modeling", "item": "Identify high-value assets", "description": "Determine which systems and data are most valuable to the organization.", "tools": "Documentation, interviews", "techniques": "Asset classification, data flow mapping, crown jewel analysis", "reference_url": "http://www.pentest-standard.org/index.php/Threat_Modeling", "order_index": 20},
            {"category": "Threat Modeling", "item": "Map attack surface", "description": "Document all potential entry points and attack vectors based on gathered intelligence.", "tools": "Manual analysis, attack surface mapping tools", "techniques": "Entry point identification, trust boundary analysis, threat actor profiling", "reference_url": "http://www.pentest-standard.org/index.php/Threat_Modeling", "order_index": 21},
            # Vulnerability Analysis
            {"category": "Vulnerability Analysis", "item": "Automated vulnerability scanning", "description": "Run vulnerability scanners against in-scope targets to identify known vulnerabilities.", "tools": "Nessus, OpenVAS, Nuclei, nikto", "techniques": "Credentialed and non-credentialed scanning, plugin selection, false positive validation", "reference_url": "http://www.pentest-standard.org/index.php/Vulnerability_Analysis", "order_index": 30},
            {"category": "Vulnerability Analysis", "item": "Manual vulnerability analysis", "description": "Manually test for vulnerabilities that automated scanners miss.", "tools": "Burp Suite, manual testing", "techniques": "Logic flaw testing, authentication bypass, input validation testing", "reference_url": "http://www.pentest-standard.org/index.php/Vulnerability_Analysis", "order_index": 31},
            {"category": "Vulnerability Analysis", "item": "Validate and prioritize findings", "description": "Confirm vulnerabilities are exploitable and prioritize by risk to the organization.", "tools": "Manual validation, PoC development", "techniques": "Exploit validation, CVSS scoring, business impact assessment", "reference_url": "http://www.pentest-standard.org/index.php/Vulnerability_Analysis", "order_index": 32},
            # Exploitation
            {"category": "Exploitation", "item": "Exploit confirmed vulnerabilities", "description": "Attempt exploitation of validated vulnerabilities to demonstrate impact.", "tools": "Metasploit, manual exploits, custom scripts", "techniques": "Public exploit modification, custom payload development, evasion techniques", "reference_url": "http://www.pentest-standard.org/index.php/Exploitation", "order_index": 40},
            {"category": "Exploitation", "item": "Establish foothold", "description": "Gain initial access to target systems through exploited vulnerabilities.", "tools": "Metasploit, Cobalt Strike, Sliver, reverse shells", "techniques": "Reverse shells, web shells, implant deployment, persistence mechanisms", "reference_url": "http://www.pentest-standard.org/index.php/Exploitation", "order_index": 41},
            # Post-Exploitation
            {"category": "Post-Exploitation", "item": "Privilege escalation", "description": "Attempt to escalate from initial access to administrative or root privileges.", "tools": "LinPEAS, WinPEAS, PowerUp, SharpUp", "techniques": "Kernel exploits, misconfigurations, credential harvesting, token manipulation", "reference_url": "http://www.pentest-standard.org/index.php/Post_Exploitation", "order_index": 50},
            {"category": "Post-Exploitation", "item": "Lateral movement", "description": "Move from compromised systems to other systems in the network.", "tools": "CrackMapExec, Impacket, PsExec, Evil-WinRM", "techniques": "Pass-the-hash, pass-the-ticket, RDP, WMI, SMB relay", "reference_url": "http://www.pentest-standard.org/index.php/Post_Exploitation", "order_index": 51},
            {"category": "Post-Exploitation", "item": "Data exfiltration demonstration", "description": "Demonstrate ability to access and exfiltrate sensitive data (with appropriate authorization).", "tools": "Custom scripts, built-in OS tools", "techniques": "Database dumping, file collection, credential extraction", "reference_url": "http://www.pentest-standard.org/index.php/Post_Exploitation", "order_index": 52},
            {"category": "Post-Exploitation", "item": "Active Directory attacks", "description": "If AD is in scope, test for Kerberoasting, AS-REP roasting, delegation abuse, and ACL attacks.", "tools": "BloodHound, Rubeus, Impacket, SharpHound", "techniques": "Kerberoasting, DCSync, Golden/Silver tickets, ACL abuse", "reference_url": "http://www.pentest-standard.org/index.php/Post_Exploitation", "order_index": 53},
            # Reporting
            {"category": "Reporting", "item": "Document all findings with evidence", "description": "Create detailed documentation of each finding including screenshots, commands, and impact.", "tools": "Breachwright, screenshot tools", "techniques": "Evidence collection, reproduction steps, impact assessment", "reference_url": "http://www.pentest-standard.org/index.php/Reporting", "order_index": 60},
            {"category": "Reporting", "item": "Generate client report", "description": "Produce professional report with executive summary, detailed findings, and remediation guidance.", "tools": "Breachwright DOCX generation", "techniques": "Risk-based prioritization, clear remediation steps, executive-level summary", "reference_url": "http://www.pentest-standard.org/index.php/Reporting", "order_index": 61},
            {"category": "Reporting", "item": "Conduct debrief with client", "description": "Present findings to technical and management stakeholders with Q&A.", "tools": "Presentation slides, report walkthrough", "techniques": "Executive summary presentation, technical deep-dive, remediation planning", "reference_url": "http://www.pentest-standard.org/index.php/Reporting", "order_index": 62},
        ],
    },
    "nist_800_115": {
        "name": "NIST SP 800-115",
        "description": "Technical Guide to Information Security Testing and Assessment",
        "items": [
            # Planning
            {"category": "Planning", "item": "Define assessment objectives", "description": "Establish clear objectives aligned with organizational security goals.", "tools": "Documentation", "techniques": "Goal setting, scope definition, stakeholder alignment", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 0},
            {"category": "Planning", "item": "Define rules of engagement", "description": "Document testing boundaries, timing, notification procedures, and escalation paths.", "tools": "Templates, legal review", "techniques": "ROE development, communication planning, incident response coordination", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 1},
            # Discovery
            {"category": "Discovery", "item": "Network discovery and mapping", "description": "Identify live hosts, network topology, and routing within the target environment.", "tools": "nmap, netdiscover, arp-scan", "techniques": "Ping sweeps, ARP scanning, traceroute, network mapping", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 10},
            {"category": "Discovery", "item": "Port and service enumeration", "description": "Identify open ports and running services on discovered hosts.", "tools": "nmap, masscan, rustscan", "techniques": "TCP/UDP scanning, version detection, script scanning", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 11},
            {"category": "Discovery", "item": "OS and service fingerprinting", "description": "Determine operating systems and specific service versions on target hosts.", "tools": "nmap, p0f, Wappalyzer", "techniques": "TCP/IP fingerprinting, banner grabbing, HTTP header analysis", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 12},
            # Vulnerability Assessment
            {"category": "Vulnerability Assessment", "item": "Network vulnerability scanning", "description": "Scan network services for known vulnerabilities using automated tools.", "tools": "Nessus, OpenVAS, Qualys", "techniques": "Credentialed scanning, plugin-based detection, compliance checks", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 20},
            {"category": "Vulnerability Assessment", "item": "Web application testing", "description": "Test web applications for OWASP Top 10 and other common vulnerabilities.", "tools": "Burp Suite, OWASP ZAP, nikto", "techniques": "Injection testing, authentication testing, session management analysis", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 21},
            {"category": "Vulnerability Assessment", "item": "Wireless security assessment", "description": "If in scope, test wireless networks for encryption weaknesses and rogue access points.", "tools": "aircrack-ng, kismet, wifite", "techniques": "WPA handshake capture, deauth attacks, rogue AP detection", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 22},
            {"category": "Vulnerability Assessment", "item": "Social engineering assessment", "description": "If in scope, test human element through phishing, pretexting, or physical access attempts.", "tools": "Gophish, SET, custom phishing templates", "techniques": "Phishing campaigns, pretexting calls, physical security testing", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 23},
            # Penetration Testing
            {"category": "Penetration Testing", "item": "Exploit identified vulnerabilities", "description": "Attempt controlled exploitation to determine real-world impact of vulnerabilities.", "tools": "Metasploit, manual exploits, custom scripts", "techniques": "Exploit development, payload customization, evasion", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 30},
            {"category": "Penetration Testing", "item": "Post-exploitation assessment", "description": "Assess the impact of successful exploitation including data access and lateral movement.", "tools": "Meterpreter, Cobalt Strike, Impacket", "techniques": "Privilege escalation, credential harvesting, pivoting, data access", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 31},
            # Analysis & Reporting
            {"category": "Analysis & Reporting", "item": "Analyze and correlate findings", "description": "Correlate findings across scanning, testing, and exploitation to determine overall risk.", "tools": "Breachwright, manual analysis", "techniques": "Risk scoring, attack chain mapping, business impact assessment", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 40},
            {"category": "Analysis & Reporting", "item": "Develop remediation roadmap", "description": "Create prioritized remediation plan with short-term fixes and long-term improvements.", "tools": "Breachwright report generation", "techniques": "Risk-based prioritization, quick wins identification, strategic planning", "reference_url": "https://csrc.nist.gov/publications/detail/sp/800-115/final", "order_index": 41},
        ],
    },
    "network_pentest": {
        "name": "Network Penetration Test",
        "description": "Standard network penetration testing checklist for internal/external assessments",
        "items": [
            {"category": "Reconnaissance", "item": "DNS enumeration", "description": "Enumerate DNS records, zone transfers, and subdomain discovery.", "tools": "dig, dnsenum, subfinder, amass", "techniques": "Zone transfer (AXFR), subdomain brute force, reverse DNS", "reference_url": "", "order_index": 0},
            {"category": "Reconnaissance", "item": "WHOIS and ASN lookup", "description": "Identify domain registration, IP ranges, and autonomous system information.", "tools": "whois, bgp.he.net, ARIN", "techniques": "IP range identification, registrant information, network ownership", "reference_url": "", "order_index": 1},
            {"category": "Scanning", "item": "Full TCP port scan", "description": "Scan all 65535 TCP ports on target hosts.", "tools": "nmap, masscan, rustscan", "techniques": "SYN scan, connect scan, version detection", "reference_url": "", "order_index": 10},
            {"category": "Scanning", "item": "UDP port scan (top 100)", "description": "Scan common UDP ports for services like DNS, SNMP, NTP.", "tools": "nmap -sU", "techniques": "UDP scanning, SNMP enumeration, DNS recursion testing", "reference_url": "", "order_index": 11},
            {"category": "Scanning", "item": "Service version detection", "description": "Identify exact versions of running services for CVE lookup.", "tools": "nmap -sV, banner grabbing", "techniques": "Version fingerprinting, script scanning, manual banner analysis", "reference_url": "", "order_index": 12},
            {"category": "Enumeration", "item": "SMB enumeration", "description": "Enumerate SMB shares, users, policies, and test for null sessions.", "tools": "enum4linux, CrackMapExec, smbclient", "techniques": "Null session testing, share enumeration, user listing, password policy", "reference_url": "", "order_index": 20},
            {"category": "Enumeration", "item": "SNMP enumeration", "description": "Test for default community strings and enumerate SNMP data.", "tools": "snmpwalk, onesixtyone, snmp-check", "techniques": "Community string brute force, MIB walking, system info extraction", "reference_url": "", "order_index": 21},
            {"category": "Enumeration", "item": "LDAP enumeration", "description": "Enumerate LDAP directory for users, groups, and organizational information.", "tools": "ldapsearch, windapsearch, ad-ldap-enum", "techniques": "Anonymous bind testing, user enumeration, group membership mapping", "reference_url": "", "order_index": 22},
            {"category": "Enumeration", "item": "Web service enumeration", "description": "Enumerate web applications, directories, and technologies.", "tools": "feroxbuster, nikto, Wappalyzer", "techniques": "Directory brute force, technology fingerprinting, virtual host enumeration", "reference_url": "", "order_index": 23},
            {"category": "Exploitation", "item": "Test for known CVEs", "description": "Attempt exploitation of identified CVEs on running services.", "tools": "Metasploit, searchsploit, custom PoCs", "techniques": "CVE exploitation, version-specific attacks, proof of concept validation", "reference_url": "", "order_index": 30},
            {"category": "Exploitation", "item": "Password attacks", "description": "Test for weak and default passwords on discovered services.", "tools": "Hydra, CrackMapExec, medusa", "techniques": "Password spraying, brute force, default credentials, credential stuffing", "reference_url": "", "order_index": 31},
            {"category": "Exploitation", "item": "Man-in-the-middle testing", "description": "Test for MITM vulnerabilities such as LLMNR/NBT-NS poisoning and ARP spoofing.", "tools": "Responder, mitm6, Bettercap", "techniques": "LLMNR poisoning, NTLM relay, DNS spoofing, ARP poisoning", "reference_url": "", "order_index": 32},
            {"category": "Post-Exploitation", "item": "Credential harvesting", "description": "Extract credentials from compromised systems (SAM, LSASS, cached creds).", "tools": "mimikatz, secretsdump.py, LaZagne", "techniques": "LSASS dumping, SAM extraction, cached credential recovery, DPAPI", "reference_url": "", "order_index": 40},
            {"category": "Post-Exploitation", "item": "Lateral movement", "description": "Move to additional systems using harvested credentials or techniques.", "tools": "CrackMapExec, PsExec, Evil-WinRM, Impacket", "techniques": "Pass-the-hash, pass-the-ticket, WMI execution, RDP", "reference_url": "", "order_index": 41},
            {"category": "Post-Exploitation", "item": "Domain privilege escalation", "description": "Escalate to Domain Admin through AD attack paths.", "tools": "BloodHound, Rubeus, Impacket", "techniques": "Kerberoasting, AS-REP roasting, ACL abuse, delegation attacks", "reference_url": "", "order_index": 42},
        ],
    },
}


def get_methodology_items(methodology_key: str) -> list[dict]:
    """Get checklist items for a methodology."""
    meth = METHODOLOGIES.get(methodology_key)
    if not meth:
        return []
    return meth["items"]


def get_available_methodologies() -> dict:
    """List available methodologies with metadata."""
    return {
        key: {"name": m["name"], "description": m["description"], "item_count": len(m["items"])}
        for key, m in METHODOLOGIES.items()
    }
